### ISSUE TITLE
How to add news

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed.github.io#1]
@maxbonomi I added a README.md file with some instructions (in particular: I used jekyll to generate the lists of links to releases and documentation consistently). Could you add a couple of sentences about how to add news?

**Comment by maxbonomi** [comment]
Yes, I will do.
There is still a problem in displaying the images in the pages of the archived news

**Comment by maxbonomi** [comment]
Done instructions, I leave this open for the problem in displaying images

**Comment by GiovanniBussi** [comment]
I thought it was more complicated... good!

**Comment by maxbonomi** [comment]
fixed images -> replaced XXX.png with /XXX.png in _layouts/default.html

**Comment by maxbonomi** [comment]
Not sure it will work after moving the site to www.plumed.org.
It seems that we are not using the same syntax as in the nest:

"img width="200" src="{{ '/' | absolute_url }}nest.png"

I will check after moving the site to plumed.org
